sudo: false
language: node_js
node_js:
  - "6"
  - "8"
  - "stable"
cache:
  directories:
    - "node_modules"
env:
  global:
    - BUILD_TIMEOUT=20000
install: npm install
script: npm run build
after_success: npm run coverage
